export enum TASKS {
  production = 'production',
  collectMail = 'collectMail',
  collectKingdomPass = 'collectKingdomPass',
  sendFriendReward = 'sendFriendReward',
  getInShopFreeDailyPack = 'getInShopFreeDailyPack',
  hotAirBallon = 'hotAirBallon',
  train = 'train',
  wishingTree = 'wishingTree',
  fountain = 'fountain',
  pvp = 'pvp',
  pvpPurchaseAncientCookie = 'pvpPurchaseAncientCookie',
  superMayhem = 'superMayhem',
  tropicalIslandShip = 'tropicalIslandShip',
  tropicalIslandSunbed = 'tropicalIslandSunbed',
  tropicalIslandClearBubble = 'tropicalIslandClearBubble',
  bounties = 'bounties',
  guild = 'guild',
}
