export * from './page/groupPage';
export * from './page/page';
export * from './page/point';
export * from './screen/screen';
export * from './screen/screenConfig';
export * from './task/taskManager';
export * from './utils/color';
export * from './utils/ocr';
export * from './utils/utils';
export * from './robotmonRawAPI';
export const version = 1;